name: AventurOO Autopost (HTML)

on:
  # ⚠️ Orët janë në UTC. Verë: Tirana = UTC+2 (shih komentet).
  schedule:
    - cron: '0 6 * * *'   # 08:00 Tirana (verë)
    - cron: '0 8 * * *'   # 10:00
    - cron: '0 10 * * *'  # 12:00
    - cron: '0 12 * * *'  # 14:00
    - cron: '0 14 * * *'  # 16:00
    - cron: '0 16 * * *'  # 18:00
    - cron: '0 18 * * *'  # 20:00
    - cron: '0 20 * * *'  # 22:00
    - cron: '0 22 * * *'  # 00:00 (dita pasuese lokale)
    - cron: '0 0 * * *'   # 02:00 (dita pasuese lokale)
  workflow_dispatch: {}    # lejo nisje manuale

permissions:
  contents: write          # push/commit në branch
  pull-requests: write     # krijo PR

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate posts from RSS
        run: |
          python3 autopost/rss_to_html.py

      - name: Configure Git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit changes (if any)
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: autopost new article"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: autopost/bot-update
          title: "Autopost: new articles"
          commit-message: "chore: autopost new article"
          body: "This PR was created automatically by the autopost workflow."
          labels: automation
          delete-branch: true
