name: AventurOO Autopost (JSON)

on:
  schedule:
    - cron: "*/30 * * * *"   # çdo 30 minuta (UTC)
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: autopost-json
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MAX_PER_CAT: "8"           # sa artikuj maksimum për kategori / run
      MAX_TOTAL: "0"             # 0 = pa limit global (ose p.sh. "24")
      SUMMARY_WORDS: "450"       # ~450 fjalë
      MAX_POSTS_PERSIST: "200"   # ruaj max 200 postime në data/posts.json
      HTTP_TIMEOUT: "15"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run autoposter
        run: python3 autopost/rss_to_html.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/posts.json autopost/seen.json || true
          if ! git diff --cached --quiet; then
            git commit -m "autopost: update posts.json"
            git push
          else
            echo "No changes to commit."
          fi