name: Autopost

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"
    - cron: "30 1,4,7,10,13,16,19,22 * * *"

permissions:
  contents: write

concurrency:
  group: autopost
  cancel-in-progress: false

jobs:
  ingest:
    name: Ingest ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: News
            script: pull_news.py
            feeds: autopost/feeds_news.txt
            category: News
            max_per_cat: "10"
            summary_words: "900"
            order: "01"
          - name: Crypto
            script: pull_crypto.py
            feeds: autopost/feeds_crypto.txt
            category: Crypto
            max_per_cat: "5"
            summary_words: "900"
            order: "02"
          - name: Culture & Arts
            script: pull_cultute_arts.py
            feeds: autopost/feeds_cultute_arts.txt
            category: "Culture & Arts"
            max_per_cat: "10"
            summary_words: "900"
            order: "03"
          - name: Entertainment
            script: pull_entertainment.py
            feeds: autopost/feeds_entertainment.txt
            category: Entertainment
            max_per_cat: "10"
            summary_words: "900"
            order: "04"
          - name: Food & Drink
            script: pull_food_drink.py
            feeds: autopost/feeds_food_drink.txt
            category: "Food & Drink"
            max_per_cat: "10"
            summary_words: "900"
            order: "05"
          - name: Lifestyle
            script: pull_lifestyle.py
            feeds: autopost/feeds_lifestyle.txt
            category: Lifestyle
            max_per_cat: "10"
            summary_words: "900"
            order: "06"
          - name: Tech & AI
            script: pull_tech_ai.py
            feeds: autopost/feeds_tech_ai.txt
            category: "Tech & AI"
            max_per_cat: "10"
            summary_words: "900"
            order: "07"
          - name: Travel
            script: pull_travel.py
            feeds: autopost/feeds_travel.txt
            category: Travel
            max_per_cat: "10"
            summary_words: "900"
            order: "08"
    env:
      SUMMARY_WORDS: ${{ matrix.summary_words }}
      MAX_PER_CAT: ${{ matrix.max_per_cat }}
      HTTP_TIMEOUT: "18"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"
      FEEDS_FILE: ${{ matrix.feeds }}
      CATEGORY: ${{ matrix.category }}
      HOT_RETENTION_DAYS: "30"
      HOT_PAGINATION_SIZE: "12"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch head
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin
          git reset --hard "origin/${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade 'pip<24.3'
          pip install trafilatura readability-lxml lxml certifi

      - name: Restore autopost state marker
        if: ${{ matrix.order != '01' }}
        id: prev
        shell: bash
        env:
          MATRIX_ORDER: ${{ matrix.order }}
        run: |
          current=${MATRIX_ORDER#0}
          if [ -z "$current" ]; then
            current=0
          fi
          prev=$(printf '%02d' $((current - 1)))
          echo "name=autopost-state-${prev}" >> "$GITHUB_OUTPUT"

      - name: Download previous autopost state
        if: ${{ matrix.order != '01' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.prev.outputs.name }}
          path: autopost-state

      - name: Apply previous autopost state
        if: ${{ matrix.order != '01' }}
        run: |
          rsync -a autopost-state/ ./
          rm -rf autopost-state

      - name: Install Node dependencies
        run: npm ci

      - name: Run autoposter
        run: python autopost/${{ matrix.script }}

      - name: Rotate hot shards into archive
        run: python scripts/rotate_hot_to_archive.py

      - name: Build site
        run: npm run build

      - name: Compress site assets
        run: npm run postbuild

      - name: Persist autopost state
        uses: actions/upload-artifact@v4
        with:
          name: autopost-state-${{ matrix.order }}
          retention-days: 3
          path: |
            _site
            _health
            data
            autopost/seen_all.json

  commit:
    name: Commit updated content
    runs-on: ubuntu-latest
    needs: ingest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch head
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin
          git reset --hard "origin/${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"

      - name: Download autopost states
        uses: actions/download-artifact@v4
        with:
          pattern: autopost-state-*
          path: autopost-artifacts
          merge-multiple: false

      - name: Apply latest autopost state
        run: |
          set -euo pipefail
          latest=$(ls autopost-artifacts | sort | tail -n1)
          rsync -a "autopost-artifacts/${latest}/" ./
          rm -rf autopost-artifacts

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "autopost: update content"
            git push origin "HEAD:${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"
          fi
