name: Autopost

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

concurrency:
  group: autopost
  cancel-in-progress: false

jobs:
  autopost:
    name: Run autopost pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync branch head
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin
          git reset --hard "origin/${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run autopost pipeline
        run: python scripts/your_autopost_pipeline.py

      - name: Build feeds
        run: python scripts/build_feeds.py

      - name: Validate feeds
        run: python scripts/validate_feeds.py

      - name: Upload autopost debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: autopost-debug
          path: data/index.json
          retention-days: 1

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "autopost: update content"
            git push origin "HEAD:${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"
          fi
