name: Autopost • Lifestyle
on:
  workflow_dispatch: {}
  schedule:
    - cron: "20,50 * * * *"  # UTC

permissions:
  contents: write

concurrency:
  group: autopost-lifestyle
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUMMARY_WORDS: "700"
      MAX_PER_CAT: "6"
      HTTP_TIMEOUT: "18"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"
      PYTHONUTF8: "1"
      PYTHONPATH: "${{ github.workspace }}/src"   # <<< KËTU vendoset që Python të gjejë 'aventuroo'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install trafilatura readability-lxml lxml certifi

      - name: Ensure files
        run: |
          mkdir -p src/aventuroo/autopost data
          [ -s src/aventuroo/autopost/seen_lifestyle.json ] || echo "{}" > src/aventuroo/autopost/seen_lifestyle.json
          [ -s data/posts.json ] || echo "[]" > data/posts.json
          # Sigurohu që paketa ekziston
          [ -f src/aventuroo/__init__.py ] || touch src/aventuroo/__init__.py
          [ -f src/aventuroo/autopost/__init__.py ] || touch src/aventuroo/autopost/__init__.py

      - name: Debug PYTHONPATH (opsionale)
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -c "import sys; print('sys.path=', sys.path[:5])"

      - name: Run Lifestyle autoposter
        env:
          PYTHONPATH: "${{ github.workspace }}/src"   # backup, nëse lart humbet për ndonjë arsye
        run: python -m aventuroo.autopost.pull_lifestyle

      - name: Commit & push
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "autopost(lifestyle): body html + attribution"
          git pull --rebase origin main || true
          git push origin HEAD:main
