name: AventurOO Autopost (JSON)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: autopost-json
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      MAX_PER_CAT: "8"
      MAX_TOTAL: "0"
      SUMMARY_WORDS: "450"
      MAX_POSTS_PERSIST: "200"
      HTTP_TIMEOUT: "15"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (top level)
        run: ls -la

      - name: Show autopost structure
        run: |
          echo "== autopost =="
          ls -la autopost || true
          echo "== autopost/data =="
          ls -la autopost/data || true
          echo "== feeds.txt =="
          [ -f autopost/data/feeds.txt ] && cat autopost/data/feeds.txt || echo "feeds.txt NOT FOUND"

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run autoposter
        run: python3 autopost/rss_to_html.py

      - name: Preview changed files
        run: |
          echo "== git status =="
          git status --porcelain
          echo "== data/posts.json head =="
          [ -f data/posts.json ] && head -n 50 data/posts.json || echo "data/posts.json NOT CREATED"

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/posts.json autopost/seen.json || true
          if ! git diff --cached --quiet; then
            git commit -m "autopost: update posts.json"
            git push
          else
            echo "No changes to commit."
          fi