name: AventurOO Autopost (JSON)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"   # çdo 30 minuta

permissions:
  contents: write

concurrency:
  group: autopost-json
  cancel-in-progress: true

jobs:
  autopost:
    runs-on: ubuntu-latest

    env:
      MAX_PER_CAT: "6"            # sa artikuj max PER KATEGORI për çdo run
      MAX_TOTAL: "0"              # 0 = pa limit total (p.sh. 12 për tavan)
      SUMMARY_WORDS: "450"        # gjatësi përmbledhjeje
      MAX_POSTS_PERSIST: "200"    # sa poste të ruhen gjithsej në data/posts.json
      HTTP_TIMEOUT: "15"
      AP_USER_AGENT: "Mozilla/5.0 (AventurOO Autoposter)"
      FALLBACK_COVER: "assets/img/cover-fallback.jpg"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show autopost structure
        run: |
          echo "== TREE =="
          ls -la
          echo "== autopost =="
          ls -la autopost || true
          echo "== autopost/data =="
          ls -la autopost/data || true
          echo "== feeds.txt =="
          [ -f autopost/data/feeds.txt ] && sed -n '1,120p' autopost/data/feeds.txt || echo "NO feeds.txt"
          echo "== seen.json (raw) =="
          [ -f autopost/seen.json ] && (ls -l autopost/seen.json; head -c 200 autopost/seen.json || true) || echo "NO seen.json"
          echo "== data/posts.json (head) =="
          [ -f data/posts.json ] && (ls -l data/posts.json; head -c 200 data/posts.json || true) || echo "NO posts.json"

      - name: Ensure seen.json (not empty)
        run: |
          mkdir -p autopost
          # nëse mungon OSE është bosh (size 0), shkruaj '{}'
          if [ ! -s autopost/seen.json ]; then
            echo "{}" > autopost/seen.json
          fi
          echo "== seen.json after fix =="
          ls -l autopost/seen.json
          head -c 200 autopost/seen.json || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install extractor deps
        run: |
          python -m pip install --upgrade pip
          pip install trafilatura lxml certifi

      - name: Run autoposter
        run: |
          set -e
          python3 autopost/rss_to_html.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "autopost: update data/posts.json & seen.json"
            git push
          fi
