name: Rotate hot shards

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 5 * * *"

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    env:
      HOT_RETENTION_DAYS: "30"
      HOT_PAGINATION_SIZE: "12"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Rotate hot shards into archive
        run: python scripts/rotate_hot_to_archive.py

      - name: Commit & push
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data scripts/rotate_hot_to_archive.py
          if git diff --cached --quiet; then
            echo "No rotation changes."
          else
            git commit -m "chore: rotate hot archive"
            git pull --rebase origin "${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}" || true
            git push
          fi
